name: CD
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v6
    - name: Create NuGet packages
      run: dotnet pack -o packages -c Release src/NetTemplate.sln
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v7
      with:
        name: packages
        path: packages
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v8
      with:
        name: packages
        path: packages
    - name: Publish NuGet packages
      run: dotnet nuget push '*.nupkg' -s https://api.nuget.org/v3/index.json -k "${{ secrets.NUGET_KEY }}" --skip-duplicate
      working-directory: packages
