name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
concurrency: ci-${{ github.ref }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v6
    - name: Build
      run: dotnet build -c Release src/NetTemplate.sln
    - name: Run tests
      run: dotnet test -c Release --no-build src/NetTemplate.sln
